### ISSUE TITLE
Problems using cloudfish

### ISSUE THREAD

**Issue by jtagcat** [indianajson/cloudfish#1]
1. There seems to (no longer?) be an account number in Cloudflare.
2. With a fake account number:
  ```
  Traceback (most recent call last):
    File "/f/g/tmp/cloudfish/cloudfish.py", line 149, in <module>
      records = dns.records(args.domain,args.key,args.email,args.account,verbose)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/f/g/tmp/cloudfish/cloudfish.py", line 74, in records
      self.zone = create_j["result"]["id"]
                  ~~~~~~~~~~~~~~~~~~^^^^^^
  TypeError: 'NoneType' object is not subscriptable
  ```

**Comment by indianajson** [comment]
Per Cloudflare's current documentation you still need your Account ID to access this resource: [Cloudflare API V4 Create Zone](https://developers.cloudflare.com/api/operations/zones-post?schema_url=https%3A%2F%2Fraw.githubusercontent.com%2Fcloudflare%2Fapi-schemas%2Fmain%2Fopenapi.yaml#request-body)

To find your account ID: login to Cloudflare, click on "Websites" then look at the URL, it will look like ```https://dash.cloudflare.com/34vy7ujmnbvr45tyhn9ijbt5tgb/```

That code in the URL is your Account ID. You can also get it once you add a website (it's in a special section), but until you add a website manually to the Cloudflare website you can only get it from here. 

I'm going to add this to the ReadMe to help anyone else! Thanks for opening the issue.
